// Other imports
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// For authentication
import AuthAndReduxProvider from "@/components/AuthAndReduxProvider";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "../state/providers/reduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <AuthAndReduxProvider>{children}</AuthAndReduxProvider>
      </body>
    </html>
  );
}
